[features]
seeds = false
skip-lint = false
[programs.localnet]
gm_anchor = "2MVTdyvCHu9kdLTAr1YGyZhMALZ7YsCc7TuNpH9pVWL3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/vietvo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
